services:

  mongo:
    image: mongo:6
    container_name: taskify-mongo
    restart: always
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"

  app:
    build: .
    container_name: taskify-app
    restart: always
    ports:
      - "3000:3000"
    environment:
      MONGO_URL: mongodb://mongo:27017/todos
      ROOT_URL: http://localhost:3000
      PORT: 3000
    depends_on:
      - mongo

volumes:
  mongo-data: